### ISSUE TITLE
Constant resolution for lambda impl methods

### ISSUE THREAD

**Issue by liach** [FabricMC/unpick#17]
From FabricMC/yarn#2553, it seems that lambda methods currently aren't resolved for unpicking. I forgot where the related unpick code is, but we can just probably visit the invoke dynamic handles (bootstrap method referred in indy bytecode) and unpick the linked synthetic methods.

**Comment by Daomephsta** [comment]
> we can just probably visit the invoke dynamic handles (bootstrap method referred in indy bytecode) and unpick the linked synthetic methods.

Unpick does not follow the call stack. It visits and transforms all methods within the class it is passed. Lambdas are being visited, the cause of this issue is something else.

**Comment by Daomephsta** [comment]
The issue is as you suggested on the linked issue
> lambda methods don't explicitly override the single abstract method in the interface

**Comment by liach** [comment]
Yeah. Imo the best approach is to scan the `BootstrapMethods` attributes to add those synthetic lambda methods as overrides, which should be better than finding each indy instruction in the code attributes.

**Comment by Daomephsta** [comment]
> 
> 
> Yeah. Imo the best approach is to scan the `BootstrapMethods` attributes to add those synthetic lambda methods as overrides, which should be better than finding each indy instruction in the code attributes.

Thanks, I didn't realise that existed. Unfortunately ASM doesn't even fully read that attribute, let alone expose it nicely.

**Comment by liach** [comment]
Yeah, asm handles bootstrap methods more like the constant pool as an impl detail, so we do have to scan all methods for indy instructions and patch
